### ISSUE TITLE
Does this module still work? Payload is not defined error

### ISSUE THREAD

**Issue by rororomyboat** [dr4ke616/MMM-Dublin-Bus#3]
Getting Error:
Dublin Bus Times:
Hmm... Bus times unavailable :(

> magicmirror@2.5.0 start /home/pi/MagicMirror
> sh run-start.sh

```
Starting MagicMirror: v2.5.0
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Dublin-Bus
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ...
Server started ...
Connecting socket for: MMM-Dublin-Bus
Starting module: MMM-Dublin-Bus
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
Started dublinbus scheduler
Whoops! There was an uncaught exception...
ReferenceError: payload is not defined
    at ClientRequest.https.get (/home/pi/MagicMirror/modules/MMM-Dublin-Bus/node_helper.js:55:71)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

```

**Comment by rororomyboat** [comment]
Could be related to the web page listed in the node helper file. 

I think the URL has changed from that to something else/service is down

**Comment by dr4ke616** [comment]
As @MrCupola correctly pointed out, the API has been blocked.

A way around this is addressed in #4 

Alternatively wait and hope that the open source api comes back online.

**Comment by MrCupola** [comment]
Last update I had 
GTFS R

The current API environment is no longer able to cope with the sheer volume of requests over a 24 hour period and that is why the NTA is building a new GTFS R environment to be scalable to future proof the open source data set.

This new GTFS R project is currently being developed by the NTA and I would hope to be able to confirm a proposed go live date over the coming weeks.

 

Fair Usage
Unfortunately due to excessive repeat Real Time searches the open source API will have limited access until the new scalable GTFS R environment has been deployed in early 2019.
Regards,
